### ISSUE TITLE
키 순서가 달라서 오답으로 나오는 경우

### ISSUE THREAD

**Issue by ntopia** [simnalamburt/snucse.treasure#2]
키 리스트의 원소들은 같은데, 순서만 다른 경우에 오답으로 나옵니다.

이번 PL수업때는 키 순서가 달라도 정답으로 처리한다고 스펙에 나와있습니다.

그리고 조교님의 테스트케이스 코드에 보면
```
let check_answer m ans = 
  let res = List.sort Pervasives.compare (getReady m) in 
  let ans = List.sort Pervasives.compare ans in 
  res = ans
```
와 같이 두 리스트를 한번 정렬해주고 난 다음에 비교를 하고 있습니다.
따라서 이런 걸 반영해주어야 하지 않나... 싶네요...

근데 어떻게 고쳐야할지는 모르겠어서 PR은 못날리고
수줍게 이슈만 살짝 남기고 갑니다...

**Comment by simnalamburt** [comment]
고마워용~

**Comment by simnalamburt** [comment]
Closed by https://github.com/simnalamburt/snucse.pl/tree/master/hw4
